### ISSUE TITLE
Counterstrafe cvar for forwardmove/rightmove/upmove

### ISSUE THREAD

**Issue by ovska** [etjump/etjump#1299]
**Problem:** When holding crouch, pressing jump just removes your crouch instead of jumping unless crouch bind is also released. Same happens when holding movement keys and pressing the key to the opposite direction.
**Solution:** Add cvar to enable automatic release the previously held key, so e.g. pressing jump while crouching releases crouch, until jump key is released. This is already possible to script with `+vstr` so it makes some sense to provide this advantage to everyone who wants it.

**Comment by Aciz** [comment]
It's a nice idea, but it's not possible to do on mod side, since you cannot reliably detect pressed movement keys, it's only possible to guess it based off usercmd values, but you can't detect if you're pressing opposite forward/right/upmove keys at the same time.
