### ISSUE TITLE
etj_autoSprint is broken at < 125fps

### ISSUE THREAD

**Issue by Aciz** [etjump/etjump#1548]
If FPS is < 125, `etj_autoSprint` does not register `+sprint` as being held.

**Comment by Aciz** [comment]
A bit more context:

This is only an issue with `pmove_fixed 1` (as you'd expect). The exact issue that happens in that `pm->cmd.buttons` does not accurately represent the state of `+sprint` button in `PmoveSingle`, which causes this code to fail

https://github.com/etjump/etjump/blob/c54d3fcb3702d60377c58821ec4db351e4e1d35c/src/game/bg_pmove.cpp#L5899-L5902

If we refactor this code like so, we can hit both of the branches of the if/else statement, with autosprint turned on, and either no input whatsoever, or holding down `+sprint`.

```cpp
  // flip sprint button bit if autosprint is enabled
  if (pm->pmext->autoSprint) {
    if (pm->cmd.buttons & BUTTON_SPRINT) {
      pm->cmd.buttons &= ~BUTTON_SPRINT;
    } else {
      pm->cmd.buttons |= BUTTON_SPRINT;
    }
  }
```

I'm not entirely sure if this is even fixable in mod code, given the usercmds are coming from engine.

**Comment by ovska** [comment]
Would it be possible to reuse user's last cmd if the pmove frame comes without usercmd having updated? e.g.

```cpp
if ((time - lastTimestamp) > pmove_msec) {
  userCmd = lastFrameUserCmd;
}

lastTimestamp = time;
lastFrameUserCmd = userCmd;
```

In this case, with 43fps you would reuse each usercmd ~3 times to get 125 valid usercmds, where most of them are interpolated (sort of)
