### ISSUE TITLE
Add some simple version handling for demos, to allow compatibility layers for older demos

### ISSUE THREAD

**Issue by isRyven** [etjump/etjump#364]
We often change field meaning in entitystate or playerstate, or reusing powerups, persistent, etc indices for own needs, some little system could help address the incompatibility issues.

ETPro for instance has something like that implemented.

**Comment by Aciz** [comment]
Compatibility checker implemented in #1210 

There are likely some stuff that needs to be fixed with compatibility, I know some events are messed up in older demos for example, but the functionality to fix them is there now.
