### ISSUE TITLE
Add tracker scripting support

### ISSUE THREAD

**Issue by isRyven** [etjump/etjump#435]
Note:
* No tracker based waits will be added. 
* Waits should be entity script based only. 
* Should have player activator.

### Conditionals ###
Executes command, if conditions are met.
```js
tracker <index> <statement> <value> <command> <parm1> <parm2> ...
// can contain line breaks:
tracker <index> <statement> <value> 
    <command> <parm1> <parm2> ...
```
__\<statement\>__
* `if_equal`  
    `tracker <index> if_equal <value>`
* `if_not_equal`  
    `tracker <index> if_not_equal <value>`
* `if_greater_than`  
    `tracker <index> if_greater_than <value>`
* `if_less_than`  
    `tracker <index> if_less_than <value>`
* `if_bitset`  
    `tracker <index> if_bitset <bit_index>`
* `if_not_bitset`  
    `tracker <index> if_not_bitset <bit_index>`

__\<command\>__
* `abort`  
    Aborts the script function execution.  
    `tracker <index> if_equal <value> abort`
* `trigger`  
    Triggers script trigger event.
    `tracker <index> if_equal <value> trigger <scriptblock> <trigger_event> [<parm>]`
    __\<scriptblock\>__:
    * `self `
    * `global`
    * valid string name
* `print` 
    With extended #410 support.
    `tracker <index> if_equal <value> print <message> [<channel> [<position>]]`
* `set`  
    Sets tracker value for a specified index.  
    `tracker <index> if_equal <value> set <index> <value>`  
    `tracker <index> if_equal <value> set <value>` sets value on first index
* `inc`  
    Increments tracker value on specified index.
    `tracker <index> if_equal <value> inc <index> <value>`  
    `tracker <index> if_equal <value> inc <value>` increments value on first index
* `bitset`  
    Sets tracker bit value on bit index for a specified tracker index.  
    `tracker <index> if_equal <value> bitset <index> <bit_index>`  
    `tracker <index> if_equal <value> bitset <bit_index>` set bit on on the first index
* `bitreset`  
    Resets tracker bit value on bit index for a specified tracker index.  
    `tracker <index> if_equal <value> bitreset <index> <bit_index>`   
    `tracker <index> if_equal <value> bitreset <bit_index>` resets bit on the first index  
* `killplayer`, `damageplayer` 
* any other standard script command?

### modification ###
`tracker <index> <operator> <value>`

__\<operator\>__:
* `set`
    Sets player's tracker value on a specified index.
    `tracker <index> set <value>`
* `inc`
    Increases player's tracker value by a number on a specifed index.
    `tracker <index> inc <value>`
* `bitset`
    Sets bit on a bit index of a player's tracker value on a specified index.
    `tracker <index> bitset <bit_index>`
* `bitset`
    Sets bit on a bit index of a player's tracker value on a specified index.
    `tracker <index> bitset <bit_index>`
* `bitreset`
    Resets bit on a bit index of a player's tracker value to zero on a specified index.
    `tracker <index> bitreset <bit_index>`

```js
RunTimer {
    activate allies {
        tracker 1 if_less_than 2 abort
        starttimer timerun1
    }
}

KillWall {
    activate allies {
        tracker 1 if_less_than 2
            print "%s you are not allowed to enter here" player center
        tracker 1 if_less than 2 killplayer
    }
}

Button {
    activate allies {
        tracker 1 if_equals 2 trigger self run
    }
    trigger run {
        print "%s has somewhere opened the door..." global popup
    }
}
```

**Comment by Aciz** [comment]
Implemented in #1207
