### ISSUE TITLE
Custom map scripts are case sensitive on Linux

### ISSUE THREAD

**Issue by isRyven** [etjump/etjump#437]
~~so if you are trying to load script name that matches map name which also uses mixed cases it wont load it, or something like that, i don't remember details, but Jay reported that 2 months ago, but i forgot to file it, i will correct the details later.~~

Custom map scripts are case sensitive on Linux, but not on Windows. Fix so that Linux doesn't care about case sensitivity.

**Comment by Aciz** [comment]
Has this been fixed? I can't reproduce on current master but can on my 2.3.0 server.

**Comment by isRyven** [comment]
because Windows is case insensitive, hence you can't reproduce that locally, but can on your server

**Comment by Aciz** [comment]
I see, so it's a Linux problem then

**Comment by ensiform** [comment]
I don't know if there is any easy solution for this as filesystem calls are basically handled at the OS level for reading/opening.
