### ISSUE TITLE
Check for the widescreen issue

### ISSUE THREAD

**Issue by isRyven** [etjump/etjump#438]
![image](https://user-images.githubusercontent.com/14905030/47605076-8fafee80-da0a-11e8-963f-582157d9aaac.png)

Is this still presents?

**Comment by Aciz** [comment]
This bug also affects fireteam menu drawing, noticed by hazz.

**Comment by isRyven** [comment]
yeah it affects everything that is drawn by the ui draw tools from the cgame, globals are evil
