### ISSUE TITLE
Player transparency works incorrectly in maps with fog

### ISSUE THREAD

**Issue by Aciz** [etjump/etjump#444]
Probably a shader related bug; if a map has fog, players are not fully opaque and become more transparent the further away you are from them.

**Comment by ensiform** [comment]
Does this affect all engines? Or only ETe?

**Comment by Aciz** [comment]
Never actually tested with ETe before, but yes, it happens on 2.60b, ETe and ETLegacy.

**Comment by ensiform** [comment]
The usage of depthWrite (writing to the depth buffer) in shaders for 'world' objects with alpha causes all sorts of potential for alpha sorting hell and pretty much guarantees this problem cannot be fixed without a new way to render the models you want in custom engine and avoiding depthWrite. Adding sort parameter may solve it but then you still have to micromanage the different sorting levels for each instance.

**Comment by Aciz** [comment]
Unfixable.
