### ISSUE TITLE
Release 2.5.0

### ISSUE THREAD

**Issue by isRyven** [etjump/etjump#558]
Main guidelines:

* This release should be dedicated to bug fixing, refactoring and code optimizations to ensure build stability.
* We should rewrite/refactor/decouple some of the (ideally all) existing ETJump pieces using `C++` and OOP, and increase the test coverage. 
* We should refrain from adding major features.
* We should ensure that any `G_Error` or `CG_Error` called at any time of the execution won't crash the client or server without apparent reason.
* We should allow ETJump features to be easily removed from the compiled binaries by reconfiguring CMake variables.
* We may add UI improvements to ensure quality UX.  
* We should consider enhancing timerun feature by:
	* Adding checkpoint support.
	* Improving timerun (end/checkpoint) printings.
	* Adding visual indicators for timerun start/end/checkpoint.
* We should consider finishing the trickjump lines by:
	* Adding feature documentation.
	* Improving existing commands and their outputs - refactoring the code (consider unit test the code).
	* Adding visual window to control the recording state.
	* Improving line segments stitching.
	* Applying any other possible optimizations.

**Comment by suburbski** [comment]
Revert #696 before release

**Comment by Aciz** [comment]
Revert #700  too.
