### ISSUE TITLE
Add option to bypass wait time in func_static pain-activation

### ISSUE THREAD

**Issue by ovska** [etjump/etjump#581]
Currently `wait` key only affects time added on top of the default wait time.

**Comment by Aciz** [comment]
Might cause issues with too rapid activation (mg42 firing for example), need to check that first.

**Comment by Aciz** [comment]
webhook test

**Comment by Aciz** [comment]
Might cause issues with too rapid activation (mg42 firing for example), need to check that first.

**Comment by Aciz** [comment]
closed via #582
