### ISSUE TITLE
64-bit binary names do not follow common idtech3 naming scheme on Windows

### ISSUE THREAD

**Issue by Aciz** [etjump/etjump#707]
x64 binary names on Windows should be
```
cgame_mp_x86_64.dll
ui_mp_x86_64.dll
qagame_mp_x86_64.dll
```

but we have
```
cgame_mp_x64.dll
ui_mp_x64.dll
qagame_mp_x64.dll
```

**Comment by isRyven** [comment]
Currently we're following naming scheme implied by the ETLegacy. So we should first see if some changes can be done on their side.

**Comment by Aciz** [comment]
Staying with this for now.
