### ISSUE TITLE
Load of garbage value upon fireteam creation

### ISSUE THREAD

**Issue by suburbski** [etjump/etjump#820]
```c
../src/game/g_fireteams.cpp:218:18: runtime error: load of value 16843009, which is not a valid value for type 'qboolean'
```

https://github.com/etjump/etjump/blob/bf94341047ff878f52ef35890df1925ecb25bcc8/src/game/g_fireteams.cpp#L218

**Comment by Aciz** [comment]
Related I believe https://stackoverflow.com/questions/19707820/memset-not-working
