### ISSUE TITLE
Division by zero in TimerunView draw

### ISSUE THREAD

**Issue by suburbski** [etjump/etjump#854]
```cpp
../src/cgame/etj_timerun_view.cpp:130:36: runtime error: division by zero
```

https://github.com/etjump/etjump/blob/9beb932660ba1867bd3901e30f6fd1449f4bfb4c/src/cgame/etj_timerun_view.cpp#L130

**Comment by Aciz** [comment]
This is no longer possible with the new range calculation that was added in #1071
