### ISSUE TITLE
Issues related to client and server side fps

### ISSUE THREAD

**Issue by Aciz** [etjump/etjump#894]
There are several things in the game code that are dependant on fps, both on client (`com_maxfps`) and server (`sv_fps`). The client side issues are of course currently affecting everyone, but these issues aren't (in the context of ETJump) that severe, however we should fix them regardless. The bigger problems come from server side fps dependencies. The biggest issue of them all is mapscripts - the `wait` key is tied to `sv_fps`. This is the main blockade of us running servers on higher than `sv_fps 20`.

The issue with mapscripts is as said, `wait` being tied to `sv_fps 20`. This cannot really be fixed per se, however we should implement a system that compensates for it. For example, right now with `sv_fps 20`, if you specify `wait 101` in mapscript, in reality this wait is going to be `wait 150`. This is because the server simply updates 20 times per second, meaning __50ms__ frametimes. So in such scenario, `wait 101` effectively turns into `wait 150`, because on the first frame there will be __51ms__ remaining on wait, second frame __1ms__, 3rd frame wait is over -> action is executed, however this is delayed by __49ms__ from the specififed time in the mapscript. In contrast to say running a server at `sv_fps 125`, we're getting __8ms__ frametimes on server. This means that eventually during that wait period, we'll land at a scenario where we have waited for __96ms__ (12 frames on `sv_fps 125`) and the next server frame will be at __104ms__ -> wait is over, action gets executed, but this time it will be __46ms__ earlier than on `sv_fps 20`.

To compensate for this, we should treat all (old) mapscripts as if the server is running at `sv_fps 20`. This means checking the server framerate in the `wait` code, and adjusting the real wait time so that it roughly aligns how things work at `sv_fps 20`, since that's what they were designed for. Assuming we're aiming for `sv_fps 125` servers, we cannot perfectly match things 1:1, for example for __50ms__ wait, the closest real wait we can do with `sv_fps 125` is either __48ms__ or __56ms__ (we should probably always round up). This difference will be so small though that it should not affect gameplay. For future maps, we could add a new implementation of `wait` key, or a script action that will tell the mod what fps the script should run at. This way new maps can take advantage of more precise `wait` times, while maintaining backwards compatibility with old maps. As a gradual effort, we can even start fixing up some old mapscripts to work properly with high fps.

A lot of work has already been done regarding fps dependency fixes in ET: Legacy, so we can farily easily port those fixes into ETJump. From the top of my head, the following things need fixing:

__Client side issues - `com_maxfps` related__

* [x] Weapon recoil
* [x] Weapon overheating
* [x] Particle effects rendering (e.g. `target_smoke`)
* [x] ~~`wait` and `await` client commands (though this is sort of by design)~~ won't fix
* [x] Stamina recovery
* [x] Bobcycle
* [x] PM_DeadMove
* [x] Explosion screenshakes

__Server side issues - `sv_fps` related__

* [x] `wait` key in mapscripts
* [x] Flamethrower firing range
* [x] Uniform stealing
* [x] Projectile collision with skyboxes (technically it's sort of broken already, but issue is exaggerated with high `sv_fps`)
* [x] ~~Lagometer~~ our lagometer isn't `sv_fps` dependent
* [x] WolfRevivePushEnt
* [x] ~~Visual bug in pause timer~~ Irrelevant, we don't have pauses
* [x] ~~Engineer pliers (unsure if this is broken at all? needs testing)~~ not broken

I am gonna go ahead and tag @ryzyk-krzysiek here, since you are the author of most of the fps dependency fixes in ET: Legacy, could you list out some of the things that I have missed that need to be untied from fps?

**Comment by ryzyk-krzysiek** [comment]
Client side issues were mostly pmove related so since ETJump uses `pmove_fixed` with 8msec it runs fine IIRC. But if you wish to fix them anyway I can list what was done in legacy (excluding what you already posted):

Pmove (`com_maxfps`):
- stamina recovery
- weapon overheating
- bobcycle (footsteps, weapon swaying)
- PM_DeadMove

Cgame (`com_maxfps`):
- screenshake from explosions

Server (`sv_fps`):
- pause
- lagometer
- WolfRevivePushEnt (not fixed in legacy)
- eng pliers (not sure about that one, but it could be broken on VET but was already fixed in legacy before I started looking into it)

`sv_fps` related issue https://github.com/etlegacy/etlegacy/issues/1637
There is no `com_maxfps` related issue sadly.

**Comment by Aciz** [comment]
> Client side issues were mostly pmove related so since ETJump uses `pmove_fixed` with 8msec it runs fine IIRC. But if you wish to fix them anyway I can list what was done in legacy (excluding what you already posted):
> 
> Pmove (`com_maxfps`):
> 
>     * stamina recovery
> 
>     * weapon overheating
> 
>     * bobcycle (footsteps, weapon swaying)
> 
>     * PM_DeadMove
> 
> 
> Cgame (`com_maxfps`):
> 
>     * screenshake from explosions
> 
> 
> Server (`sv_fps`):
> 
>     * pause
> 
>     * lagometer
> 
>     * WolfRevivePushEnt (not fixed in legacy)
> 
>     * eng pliers (not sure about that one, but it could be broken on VET but was already fixed in legacy before I started looking into it)
> 
> 
> `sv_fps` related issue [etlegacy/etlegacy#1637](https://github.com/etlegacy/etlegacy/issues/1637) There is no `com_maxfps` related issue sadly.

Thanks, out of these we can definitely ignore the pause issue as we don't really support it anyway (idk at this point if it's even functional). What was the issue with pliers, I don't recall that, faster building?

**Comment by ryzyk-krzysiek** [comment]
> What was the issue with pliers, I don't recall that, faster building?
I somewhat remember that it might have been the case in VET, but not sure really but shouldn't be hard to test if it is.

**Comment by Aciz** [comment]
> > What was the issue with pliers, I don't recall that, faster building?
> 
> I somewhat remember that it might have been the case in VET, but not sure really but shouldn't be hard to test if it is.

From a very quick test it seems it's not affected by sv_fps at least in ETJump, but I'll keep it in mind.
